substitutions:
  name: "grpm2"
  device_type: "ESP32-C6-H4"
  device_comment: "Power Meter"
  disp_name: "GRPM2"
  update_time: 15s
  line_frequency: 60Hz # Default
  gain_pga: 1X # Defualt

  # SPI CS Pins
  main_spi_cs_pin: GPIO23
  riser1_spi_cs_pin: GPIO0
  riser2_spi_cs_pin: GPIO1
  riser3_spi_cs_pin: GPIO2
  riser4_spi_cs_pin: GPIO3
  riser5_spi_cs_pin: GPIO10

  main_chip_id: IC1
  riser1_chip_id: IC2
  riser2_chip_id: IC3
  riser3_chip_id: IC4
  riser4_chip_id: IC5
  riser5_chip_id: IC6

  main_phase_a_ct_name: CT1
  main_phase_b_ct_name: CT2
  main_phase_c_ct_name: CT3
  main_phase_a_line_name: L1
  main_phase_b_line_name: L2
  main_phase_c_line_name: L3
  main_phase_a_voltage_cal: 4200
  main_phase_b_voltage_cal: 4200
  main_phase_c_voltage_cal: 4200
  main_phase_a_current_cal: 14200
  main_phase_b_current_cal: 14200
  main_phase_c_current_cal: 14200
  main_enable_gain_calibration: true
  main_enable_offset_calibration: true
  main_gain_pga: ${gain_pga}

# Riser1 board variables
  riser1_phase_a_ct_name: CT4
  riser1_phase_b_ct_name: CT5
  riser1_phase_c_ct_name: CT6
  riser1_phase_a_line_name: L4
  riser1_phase_b_line_name: L5
  riser1_phase_c_line_name: L6
  riser1_phase_a_voltage_cal: 4200
  riser1_phase_b_voltage_cal: 4200
  riser1_phase_c_voltage_cal: 4200
  riser1_phase_a_current_cal: 14200
  riser1_phase_b_current_cal: 14200
  riser1_phase_c_current_cal: 14200
  riser1_enable_gain_calibration: true
  riser1_enable_offset_calibration: true
  riser1_gain_pga: ${gain_pga}

# Riser2 board variables
  riser2_phase_a_ct_name: CT7
  riser2_phase_b_ct_name: CT8
  riser2_phase_c_ct_name: CT9
  riser2_phase_a_line_name: L7
  riser2_phase_b_line_name: L8
  riser2_phase_c_line_name: L9
  riser2_phase_a_voltage_cal: 4200
  riser2_phase_b_voltage_cal: 4200
  riser2_phase_c_voltage_cal: 4200
  riser2_phase_a_current_cal: 14200
  riser2_phase_b_current_cal: 14200
  riser2_phase_c_current_cal: 14200
  riser2_enable_gain_calibration: true
  riser2_enable_offset_calibration: true
  riser2_gain_pga: ${gain_pga}

# Riser3 board variables
  riser3_phase_a_ct_name: CT10
  riser3_phase_b_ct_name: CT11
  riser3_phase_c_ct_name: CT12
  riser3_phase_a_line_name: L10
  riser3_phase_b_line_name: L11
  riser3_phase_c_line_name: L12
  riser3_phase_a_voltage_cal: 4200
  riser3_phase_b_voltage_cal: 4200
  riser3_phase_c_voltage_cal: 4200
  riser3_phase_a_current_cal: 14200
  riser3_phase_b_current_cal: 14200
  riser3_phase_c_current_cal: 14200
  riser3_enable_gain_calibration: true
  riser3_enable_offset_calibration: true
  riser3_gain_pga: ${gain_pga}

# Riser4 board variables
  riser4_phase_a_ct_name: CT13
  riser4_phase_b_ct_name: CT14
  riser4_phase_c_ct_name: CT15
  riser4_phase_a_line_name: L13
  riser4_phase_b_line_name: L14
  riser4_phase_c_line_name: L15
  riser4_phase_a_voltage_cal: 4200
  riser4_phase_b_voltage_cal: 4200
  riser4_phase_c_voltage_cal: 4200
  riser4_phase_a_current_cal: 14200
  riser4_phase_b_current_cal: 14200
  riser4_phase_c_current_cal: 14200
  riser4_enable_gain_calibration: true
  riser4_enable_offset_calibration: true
  riser4_gain_pga: ${gain_pga}

# Riser5 board variables
  riser5_phase_a_ct_name: CT16
  riser5_phase_b_ct_name: CT17
  riser5_phase_c_ct_name: CT18
  riser5_phase_a_line_name: L16
  riser5_phase_b_line_name: L17
  riser5_phase_c_line_name: L18
  riser5_phase_a_voltage_cal: 4200
  riser5_phase_b_voltage_cal: 4200
  riser5_phase_c_voltage_cal: 4200
  riser5_phase_a_current_cal: 14200
  riser5_phase_b_current_cal: 14200
  riser5_phase_c_current_cal: 14200
  riser5_enable_gain_calibration: true
  riser5_enable_offset_calibration: true
  riser5_gain_pga: ${gain_pga}

packages:
  - !include packages/grpm2.main.yaml
  - !include packages/grpm2.main.totals.yaml
  - !include packages/grpm2.riser1.yaml
  - !include packages/grpm2.riser1.totals.yaml
  - !include packages/grpm2.riser2.yaml
  - !include packages/grpm2.riser2.totals.yaml
  - !include packages/grpm2.riser3.yaml
  - !include packages/grpm2.riser3.totals.yaml
  - !include packages/grpm2.riser4.yaml
  - !include packages/grpm2.riser4.totals.yaml
  - !include packages/grpm2.riser5.yaml
  - !include packages/grpm2.riser5.totals.yaml

esphome:
  name: ${name}
  friendly_name: ${disp_name}
  name_add_mac_suffix: true # Used for shipping images
  project:
    name: "GRPM2.Energy_Meter"
    version: "1.0.0"

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: n

logger:

api:

ota:
  - platform: esphome

wifi:
  ap:
    password: ""
    ap_timeout: 15s

captive_portal:

preferences:
  flash_write_interval: 300s

web_server:
  port: 80
  version: 3

spi:
  clk_pin: 19
  miso_pin: 22
  mosi_pin: 20

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: template
    name: ${disp_name} Total Amps
    id: totalAmps
    lambda: return id(totalAmps${main_chip_id}).state + id(totalAmps${riser1_chip_id}).state + id(totalAmps${riser2_chip_id}).state + id(totalAmps${riser3_chip_id}).state + id(totalAmps${riser4_chip_id}).state + id(totalAmps${riser5_chip_id}).state;
    accuracy_decimals: 2
    unit_of_measurement: A
    device_class: current
    update_interval: ${update_time}

  - platform: template
    name: ${disp_name} Total Watts
    id: totalWatts
    lambda: return id(totalWatts${main_chip_id}).state + id(totalWatts${riser1_chip_id}).state + id(totalWatts${riser2_chip_id}).state + id(totalWatts${riser3_chip_id}).state + id(totalWatts${riser4_chip_id}).state + id(totalWatts${riser5_chip_id}).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}

  - platform: total_daily_energy
    name: ${disp_name} Total kWh
    power_id: totalWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
